// A separate file just for your words!
// You can add thousands of words here.
const wordBankData = [
    // --- SPACE THEME ---
    { word: "STAR", clue: "A glowing ball of gas in space" },
    { word: "MOON", clue: "Earth's natural satellite" },
    { word: "SUN", clue: "The center of our solar system" },
    { word: "GALAXY", clue: "A massive system of stars, like the Milky Way" },
    { word: "COMET", clue: "Ice rock with a tail" },
    { word: "ASTEROID", clue: "Small rocky body orbiting the sun" },
    { word: "NEBULA", clue: "Giant cloud of dust and gas" },
    { word: "BLACKHOLE", clue: "Nothing escapes its gravity" },
    { word: "ECLIPSE", clue: "When one celestial body blocks another" },
    { word: "ORBIT", clue: "Curved path around a star" },
    { word: "GRAVITY", clue: "Force that pulls objects down" },
    { word: "ROCKET", clue: "Vehicle for space travel" },
    { word: "ASTRONAUT", clue: "Person who travels to space" },
    { word: "TELESCOPE", clue: "Tool to see far away things" },
    { word: "MARS", clue: "The Red Planet" },
    { word: "VENUS", clue: "The Hottest Planet" },
    { word: "JUPITER", clue: "The Largest Planet" },
    { word: "SATURN", clue: "The Ringed Planet" },
    { word: "PLUTO", clue: "The famous dwarf planet" },
    { word: "CONSTELLATION", clue: "Group of stars forming a pattern" },
    { word: "SUPERNOVA", clue: "Explosion of a star" },
    { word: "ZODIAC", clue: "Circle of animals in the sky" },
    { word: "COSMOS", clue: "The universe seen as an orderly whole" },
    { word: "METEOR", clue: "A streak of light from a rock burning in Earth's atmosphere" },
    { word: "ASTROLABE", clue: "Ancient tool for measuring stars" },
    { word: "SATELLITE", clue: "Object orbiting a planet" },
    { word: "AURORA", clue: "Glowing lights in polar skies" },
    { word: "EXOPLANET", clue: "A planet outside our solar system" },
    { word: "UNIVERSE", clue: "All space, time, and matter" },
    { word: "COSMONAUT", clue: "Russian space traveler" },
    { word: "MODULE", clue: "Part of a spacecraft" },
    { word: "SPACETIME", clue: "The fabric combining space and time" },

    // --- NATURE THEME ---
    { word: "FLOWER", clue: "The reproductive part of a plant" },
    { word: "TREE", clue: "Tall plant with a trunk" },
    { word: "FOREST", clue: "Large area covered with trees" },
    { word: "OCEAN", clue: "Large body of salt water" },
    { word: "RIVER", clue: "Flowing body of fresh water" },
    { word: "MOUNTAIN", clue: "Large natural elevation of earth" },
    { word: "VALLEY", clue: "Low area between hills" },
    { word: "DESERT", clue: "Dry barren area of land" },
    { word: "RAIN", clue: "Water falling from clouds" },
    { word: "STORM", clue: "Violent weather disturbance" },
    { word: "THUNDER", clue: "Sound caused by lightning" },
    { word: "CLOUD", clue: "Visible mass of condensed water vapor" },
    { word: "WIND", clue: "Moving air" },
    { word: "SNOW", clue: "Frozen rain" },
    { word: "SPRING", clue: "Season after winter" },
    { word: "SUMMER", clue: "The hottest season" },
    { word: "AUTUMN", clue: "Season when leaves fall" },
    { word: "WINTER", clue: "The coldest season" },
    { word: "GARDEN", clue: "Plot of ground for growing plants" },
    { word: "MEADOW", clue: "Field of grass" },
    { word: "ISLAND", clue: "Land surrounded by water" },
    { word: "LAGOON", clue: "Shallow body of water separated from the sea" },
    { word: "VOLCANO", clue: "Mountain that erupts lava" },
    { word: "GLACIER", clue: "Large mass of moving ice" },
    { word: "WILDFIRE", clue: "Large uncontrolled fire" },
    { word: "CORAL", clue: "Marine organism forming reefs" },
    { word: "BREEZE", clue: "Light wind" },
    { word: "EARTHQUAKE", clue: "Sudden shaking of the ground" },
    { word: "TSUNAMI", clue: "Large ocean wave caused by underwater disturbance" },
    { word: "RAINFOREST", clue: "Dense forest with high rainfall" },
    
    // --- GENERAL ---
    { word: "DREAM", clue: "Thoughts while sleeping" },
    { word: "MAGIC", clue: "Supernatural power" },
    { word: "PUZZLE", clue: "A game designed to test ingenuity" },
    { word: "MYSTERY", clue: "Something difficult to understand" },
    { word: "SHADOW", clue: "Dark shape cast by an object" },
    { word: "LIGHT", clue: "Agent that stimulates sight" },
    { word: "COLOR", clue: "Property possessed by an object" },
    { word: "MUSIC", clue: "Vocal or instrumental sounds" },
    { word: "LEGEND", clue: "Traditional story sometimes believed as history" },
    { word: "SECRET", clue: "Something kept hidden" },
    { word: "JOURNEY", clue: "Act of traveling from one place to another" },
    { word: "WHISPER", clue: "Speak very softly" },
    { word: "MEMORY", clue: "Something remembered" },
    { word: "CIPHER", clue: "A coded message" },
    { word: "VISION", clue: "Ability to see" },
    { word: "SPIRIT", clue: "Non-physical essence of a being" },
    { word: "FABLE", clue: "Story with a moral" },
    { word: "ECHO", clue: "Sound reflected back" },

    // --- TECHNOLOGY --- //
    { word: "COMPUTER", clue: "Electronic device that processes data" },
    { word: "KEYBOARD", clue: "Device used to type" },
    { word: "MONITOR", clue: "Screen for displaying output" },
    { word: "SOFTWARE", clue: "Programs that run on a computer" },
    { word: "HARDWARE", clue: "Physical parts of a computer" },
    { word: "INTERNET", clue: "Global network of computers" },
    { word: "ROUTER", clue: "Device that directs internet traffic" },
    { word: "WIRELESS", clue: "Communication without cables" },
    { word: "SMARTPHONE", clue: "A mobile phone with advanced features" },
    { word: "BATTERY", clue: "Stores energy for devices" },
    { word: "GIGABYTE", clue: "Unit of digital storage" },
    { word: "PIXEL", clue: "Smallest unit of a display" },
    { word: "ANTIVIRUS", clue: "Software that protects your system" },
    { word: "UPLOAD", clue: "Send data to a server" },
    { word: "DOWNLOAD", clue: "Receive data from a server" },
    { word: "DATABASE", clue: "Structured collection of data" },
    { word: "ALGORITHM", clue: "Step-by-step process for solving problems" },
    { word: "FIREWALL", clue: "Security system that blocks harmful traffic" },
    { word: "SERVER", clue: "Provides services over a network" },
    { word: "ENCRYPTION", clue: "Scrambling data for security" },

    // --- FOOD --- //
    { word: "PIZZA", clue: "Flatbread topped with sauce and cheese" },
    { word: "BURGER", clue: "Sandwich with a meat patty" },
    { word: "PASTA", clue: "Noodles commonly served with sauce" },
    { word: "SUSHI", clue: "Japanese dish with rice and seafood" },
    { word: "SALAD", clue: "Mix of vegetables" },
    { word: "BREAD", clue: "Staple food made from dough" },
    { word: "COOKIE", clue: "Small sweet baked treat" },
    { word: "CHOCOLATE", clue: "Sweet treat made from cacao" },
    { word: "NOODLES", clue: "Long thin dough strands" },
    { word: "OMELET", clue: "Egg dish cooked in a pan" },
    { word: "CURRY", clue: "Dish with spiced sauce" },
    { word: "BARBECUE", clue: "Food cooked over fire" },
    { word: "SANDWICH", clue: "Food between two slices of bread" },
    { word: "ICECREAM", clue: "Frozen sweet dessert" },
    { word: "PANCAKE", clue: "Flat cake cooked on a griddle" },
    { word: "SOUP", clue: "Liquid dish often served warm" },
    { word: "CHEESE", clue: "Dairy product made from milk" },
    { word: "YOGURT", clue: "Fermented milk product" },
    { word: "FRIES", clue: "Deep-fried potato strips" },

    // --- ANIMALS --- //
    { word: "LION", clue: "Large cat known as the king of the jungle" },
    { word: "TIGER", clue: "Striped big cat" },
    { word: "ELEPHANT", clue: "Largest land animal" },
    { word: "GIRAFFE", clue: "Tallest land animal" },
    { word: "DOLPHIN", clue: "Intelligent marine mammal" },
    { word: "EAGLE", clue: "Bird with powerful eyesight" },
    { word: "OWL", clue: "Nocturnal bird with silent wings" },
    { word: "SNAKE", clue: "Legless reptile" },
    { word: "TURTLE", clue: "Reptile with a shell" },
    { word: "ZEBRA", clue: "Horse-like animal with stripes" },
    { word: "WOLF", clue: "Wild canine" },
    { word: "KANGAROO", clue: "Marsupial that hops" },
    { word: "PENGUIN", clue: "Bird that cannot fly" },
    { word: "HORSE", clue: "Hoofed animal used for riding" },
    { word: "SHARK", clue: "Large carnivorous fish" },
    { word: "CRAB", clue: "Sea creature with claws" },
    { word: "BUTTERFLY", clue: "Insect with colorful wings" },
    { word: "SPIDER", clue: "Eight-legged arachnid" },
    { word: "BEAR", clue: "Large omnivorous mammal" },

    // --- MYTHOLOGY --- //
    { word: "DRAGON", clue: "Legendary fire-breathing creature" },
    { word: "PHOENIX", clue: "Bird that rises from its ashes" },
    { word: "UNICORN", clue: "Horse with a single horn" },
    { word: "MERMAID", clue: "Half-human, half-fish creature" },
    { word: "GIANT", clue: "Humanoid of great size" },
    { word: "GRIFFIN", clue: "Creature with a lion's body and eagle's head" },
    { word: "CERBERUS", clue: "Three-headed dog of the underworld" },
    { word: "MINOTAUR", clue: "Half-man, half-bull" },
    { word: "PEGASUS", clue: "Winged horse" },
    { word: "TITAN", clue: "Powerful deity overthrown by the Olympians" },
    { word: "VALKYRIE", clue: "Chooser of the slain in Norse myth" },
    { word: "NYMPH", clue: "Nature spirit in Greek myth" },
    { word: "KRAKEN", clue: "Giant sea monster" },
    { word: "BASILISK", clue: "Serpent that kills with a glance" },
    { word: "HYDRA", clue: "Serpent with many heads" },

    // --- TRANSPORTATION --- //
    { word: "CAR", clue: "Four-wheeled motor vehicle" },
    { word: "TRUCK", clue: "Large vehicle for transporting goods" },
    { word: "TRAIN", clue: "Series of connected rail vehicles" },
    { word: "AIRPLANE", clue: "Aircraft with wings" },
    { word: "HELICOPTER", clue: "Aircraft with rotating blades" },
    { word: "SUBMARINE", clue: "Underwater vessel" },
    { word: "BICYCLE", clue: "Two-wheeled human-powered vehicle" },
    { word: "SCOOTER", clue: "Small motorized vehicle" },
    { word: "SHIP", clue: "Large vessel for water travel" },
    { word: "BOAT", clue: "Small vessel for water" },
    { word: "BUS", clue: "Vehicle for public transport" },
    { word: "MOTORCYCLE", clue: "Two-wheeled motor vehicle" },
    { word: "ROCKET", clue: "Vehicle for space travel" },
    { word: "CANOE", clue: "Narrow lightweight boat" },
    { word: "TRAM", clue: "Rail vehicle that runs in city streets" },

    // --- HOBBIES AND ACTIVITIES --- //
    { word: "PAINTING", clue: "Art made with colors on a surface" },
    { word: "DRAWING", clue: "Creating images with lines" },
    { word: "READING", clue: "Looking at written words" },
    { word: "WRITING", clue: "Producing text" },
    { word: "GAMING", clue: "Playing video games" },
    { word: "FISHING", clue: "Catching fish for sport" },
    { word: "COOKING", clue: "Preparing food" },
    { word: "BAKING", clue: "Cooking using an oven" },
    { word: "HIKING", clue: "Walking in nature" },
    { word: "SWIMMING", clue: "Moving through water" },
    { word: "CYCLING", clue: "Riding a bike" },
    { word: "PHOTOGRAPHY", clue: "Taking pictures" },
    { word: "SINGING", clue: "Producing vocal music" },
    { word: "DANCING", clue: "Moving rhythmically to music" },
    { word: "GARDENING", clue: "Growing plants as a hobby" },

    // --- EMOTIONS AND ABSTRACT CONCEPTS --- //
    { word: "HOPE", clue: "Feeling of expectation" },
    { word: "JOY", clue: "Great happiness" },
    { word: "ANGER", clue: "Strong feeling of annoyance" },
    { word: "PEACE", clue: "State of tranquility" },
    { word: "COURAGE", clue: "Ability to face fear" },
    { word: "FAITH", clue: "Strong belief" },
    { word: "LOVE", clue: "Strong affection" },
    { word: "CHAOS", clue: "Complete disorder" },
    { word: "ORDER", clue: "State of organization" },
    { word: "TRUTH", clue: "State of being factual" },
    { word: "WISDOM", clue: "Quality of having experience and knowledge" },
    { word: "HONOR", clue: "High respect" },
    { word: "GLORY", clue: "Great fame or achievement" },
    { word: "PATIENCE", clue: "Ability to wait calmly" },
    { word: "DESIRE", clue: "Strong feeling of wanting" },

    // --- HISTORY --- //
    { word: "EMPIRE", clue: "Group of nations under one ruler" },
    { word: "DYNASTY", clue: "Line of hereditary rulers" },
    { word: "PHARAOH", clue: "Ancient Egyptian ruler" },
    { word: "PAPYRUS", clue: "Ancient Egyptian writing material" },
    { word: "PYRAMID", clue: "Egyptian stone tomb" },
    { word: "SPARTA", clue: "Ancient Greek warrior city" },
    { word: "ATHENS", clue: "City-state known for philosophy" },
    { word: "CENTURION", clue: "Roman officer" },
    { word: "GLADIATOR", clue: "Roman fighter" },
    { word: "COLISEUM", clue: "Famous Roman arena" },
    { word: "VIKING", clue: "Norse explorer or warrior" },
    { word: "RENAISSANCE", clue: "Period of artistic revival" },
    { word: "REVOLUTION", clue: "Forcible overthrow of a government" },
    { word: "MONARCHY", clue: "Government ruled by a king or queen" },
    { word: "ARCHAEOLOGY", clue: "Study of ancient artifacts" },

    // --- GEOGRAPHY --- //
    { word: "CONTINENT", clue: "Large continuous landmass" },
    { word: "ISLAND", clue: "Land surrounded by water" },
    { word: "PENINSULA", clue: "Land almost completely surrounded by water" },
    { word: "ARCHIPELAGO", clue: "Group of islands" },
    { word: "CANYON", clue: "Deep, narrow valley with steep sides" },
    { word: "PLATEAU", clue: "High flat landform" },
    { word: "HARBOR", clue: "Sheltered area for ships" },
    { word: "DELTA", clue: "Landform at a river mouth" },
    { word: "ESTUARY", clue: "Where river meets the sea" },
    { word: "FJORD", clue: "Long, narrow sea inlet" },
    { word: "VOLCANO", clue: "Mountain that can erupt" },
    { word: "TUNDRA", clue: "Cold treeless region" },
    { word: "SAVANNA", clue: "Grassland with scattered trees" },
    { word: "OASIS", clue: "Fertile spot in a desert" },
    { word: "GLACIER", clue: "Slow-moving mass of ice" },

    // --- SPORTS --- //
    { word: "SOCCER", clue: "Sport played with a round ball" },
    { word: "BASKETBALL", clue: "Sport with hoops" },
    { word: "BASEBALL", clue: "Bat-and-ball sport" },
    { word: "TENNIS", clue: "Sport played with rackets" },
    { word: "SWIMMING", clue: "Sport done in water" },
    { word: "CYCLING", clue: "Racing with bicycles" },
    { word: "ARCHERY", clue: "Sport with bow and arrow" },
    { word: "WRESTLING", clue: "Grappling combat sport" },
    { word: "BOXING", clue: "Combat sport with gloves" },
    { word: "FOOTBALL", clue: "Sport involving touchdowns" },
    { word: "GOLF", clue: "Sport played with clubs and holes" },
    { word: "VOLLEYBALL", clue: "Sport with a net and ball" },
    { word: "SKATEBOARD", clue: "Board with wheels used for tricks" },
    { word: "GYMNASTICS", clue: "Sport of balance and flexibility" },
    { word: "KARATE", clue: "Martial art with strikes" },

    // --- FANTASY --- //
    { word: "SORCERER", clue: "User of magic" },
    { word: "SPELLBOOK", clue: "Book of magic spells" },
    { word: "ENCHANTER", clue: "Someone who uses enchantments" },
    { word: "PORTAL", clue: "Gateway to another world" },
    { word: "DUNGEON", clue: "Underground prison" },
    { word: "GOLEM", clue: "Creature made of clay or stone" },
    { word: "WIZARDRY", clue: "Practice of magic" },
    { word: "PROPHECY", clue: "Foretelling of future events" },
    { word: "RUNEBLADE", clue: "Sword carved with magic runes" },
    { word: "SHAPESHIFT", clue: "Change form magically" },
    { word: "ILLUSION", clue: "Deceptive magical appearance" },
    { word: "FAMILIAR", clue: "Magical companion animal" },
    { word: "WARLOCK", clue: "Male practitioner of magic" },
    { word: "PALADIN", clue: "Holy knight" },
    { word: "SUMMONER", clue: "Calling creatures from other realms" },

    // --- FILM AND TV --- //
    { word: "ACTOR", clue: "Performer in films or TV" },
    { word: "DIRECTOR", clue: "Person who oversees a film" },
    { word: "SCREENPLAY", clue: "Movie script" },
    { word: "CAMERA", clue: "Device used to film scenes" },
    { word: "STUDIO", clue: "Place where movies are produced" },
    { word: "SCENE", clue: "Part of a movie" },
    { word: "TRAILER", clue: "Preview of a movie" },
    { word: "BLOOPERS", clue: "Funny mistakes in filming" },
    { word: "SEQUEL", clue: "A movie that continues another" },
    { word: "PREQUEL", clue: "Story that occurs before another" },
    { word: "PILOT", clue: "First episode of a series" },
    { word: "CREDITS", clue: "List of people involved in production" },
    { word: "CINEMATOGRAPHY", clue: "Art of film photography" },
    { word: "BLOCKBUSTER", clue: "Massive hit movie" },
    { word: "ANIMATION", clue: "Movies created frame-by-frame" },

    // --- VIDEO GAME THEME --- //
    { word: "CONTROLLER", clue: "Handheld device used to play games" },
    { word: "JOYSTICK", clue: "Stick used for movement in games" },
    { word: "RESPAWN", clue: "Reappear after dying" },
    { word: "QUEST", clue: "Task given in a game" },
    { word: "LOOT", clue: "Items collected from enemies" },
    { word: "BOSSFIGHT", clue: "Battle against a major enemy" },
    { word: "LEVELUP", clue: "Increase character's power" },
    { word: "MULTIPLAYER", clue: "Game mode with multiple players" },
    { word: "RPG", clue: "Role-playing game" },
    { word: "FPS", clue: "First-person shooter" },
    { word: "STRATEGY", clue: "Game requiring planning" },
    { word: "OPENWORLD", clue: "Large map with freedom to explore" },
    { word: "SKILLTREE", clue: "Progression chart of abilities" },
    { word: "INVENTORY", clue: "List of collected items" },
    { word: "ARENA", clue: "Closed combat environment" },

    // --- LANGUAGE AND WORDS --- //
    { word: "VOCABULARY", clue: "Collection of known words" },
    { word: "DICTIONARY", clue: "Book of word meanings" },
    { word: "SYNONYM", clue: "Word with similar meaning" },
    { word: "ANTONYM", clue: "Word with opposite meaning" },
    { word: "PROVERB", clue: "Traditional saying" },
    { word: "IDIOM", clue: "Phrase with non-literal meaning" },
    { word: "GRAMMAR", clue: "Rules of language structure" },
    { word: "SYLLABLE", clue: "Unit of sound in a word" },
    { word: "PREFIX", clue: "Word part added to the beginning" },
    { word: "SUFFIX", clue: "Word part added to the end" },
    { word: "ALPHABET", clue: "Set of letters" },
    { word: "PARAGRAPH", clue: "Section of writing" },
    { word: "PUNCTUATION", clue: "Marks used in writing" },
    { word: "ACRONYM", clue: "Abbreviation formed from initials" },
    { word: "ETYMOLOGY", clue: "Study of word origins" }
];